export const START = 'start'
export const PAUSE = 'pause'
export const STOP = 'stop'
export const RESET = 'reset'
export const TICK = 'tick'
export const SELECT_CATEGORY = 'selectCategory'
export const UPDATE_TYPED_WORD = 'updateTypedWord'
export const NEXT_WORD = 'nextWord'
